ThirdVariant/ThirdVariant/Models/ErrorViewModel.cs
namespace ThirdVariant.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ThirdVariant/ThirdVariant/Models/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThirdVariant.Models
{
    public class IndexViewModel
    {
        public IEnumerable<Vacancy> Vacancies { get; set; }
        public PageViewModel PageViewModel { get; set; }
    }
}

ThirdVariant/ThirdVariant/Models/PageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThirdVariant.Models
{
    public class PageViewModel
    {
        public int PageNumber { get; private set; }
        public int TotalPages { get; private set; }

        public PageViewModel(int count, int pageNumber, int pageSize)
        {
            PageNumber = pageNumber;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        }

        public bool HasPreviousPage
        {
            get
            {
                return (PageNumber > 1);
            }
        }

        public bool HasNextPage
        {
            get
            {
                return (PageNumber < TotalPages);
            }
        }
    }
}

ThirdVariant/ThirdVariant/Models/Vacancy.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ThirdVariant.Models
{
    [Table("v_get_vacany_body")]
    public class Vacancy
    {
        [Key]
        public int id { get; set; }
        public string vacancy_id { get; set; }
        [Display(Name = "Vacancy Name")]
        public string vacancy_name { get; set; }
        public string description { get; set; }
        public string schedule { get; set; }
        public string experience { get; set; }
        public string department { get; set; }
        public string employment { get; set; }
        public string salary_to { get; set; }
        public string salary_from { get; set; }
        public string salary_currency { get; set; }
        public string area_name { get; set; }
        public string employer_name { get; set; }
        public DateTime published_at { get; set; }

    }
}

ThirdVariant/ThirdVariant/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ThirdVariant.Models;

namespace ThirdVariant.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        //private IVacancyRepository vacancyRepository;

        //public HomeController()
        //{
        //    this.vacancyRepository = new VacancyRepository(new VacancyContext());
        //}

        //public HomeController(IVacancyRepository vacancyRepository)
        //{
        //    this.vacancyRepository = vacancyRepository;
        //}


        ////GET: /Vacancy/

        //public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        //{
        //    ViewBag.CurrentSort = sortOrder;
        //    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

        //    if (searchString != null)
        //    {
        //        page = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }
        //    ViewBag.CurrentFilter = searchString;

        //    var vacancies = from s in vacancyRepository.GetVacancies()
        //                    select s;
        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        vacancies = vacancies.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper()));
        //    }
        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            vacancies = vacancies.OrderByDescending(s => s.Name);
        //            break;
        //        case "Date":
        //            vacancies = vacancies.OrderBy(s => s.PublishedAt);
        //            break;
        //        case "date_desc":
        //            vacancies = vacancies.OrderByDescending(s => s.PublishedAt);
        //            break;
        //        default:  // Name ascending 
        //            vacancies = vacancies.OrderBy(s => s.Name);
        //            break;
        //    }

        //    int pageSize = 3;
        //    int pageNumber = (page ?? 1);
        //    return View(vacancies.ToPagedList(pageNumber, pageSize));
        //}

        ////public ViewResult Details(int id)
        ////{
        ////    Vacancy vacancy = vacancyRepository.GetVacancyById(id);
        ////    return View(vacancy);
        ////}
    }
}

ThirdVariant/ThirdVariant/Controllers/VacancyController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

//using Sakura.AspNetCore;
using ThirdVariant.DAL;
using ThirdVariant.Models;

namespace ThirdVariant.Controllers
{
    public class VacancyController : Controller
    {
        private IVacancyRepository vacancyRepository;

        public VacancyController()
        {
            vacancyRepository = new VacancyRepository(new VacancyContext());
        }


        public ViewResult Index(string sortOrder, string currentFilter, string searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                Vars.GetVacanciesFromHh();

            }
                    
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            
            ViewBag.CurrentFilter = searchString;

            var vacancies = vacancyRepository.GetVacancies().Select(s => s).Take(15);

            if (!String.IsNullOrEmpty(searchString))
            {
                vacancies = vacancies.Where(s => s.vacancy_name.ToUpper().Contains(searchString.ToUpper()));

            }
            switch (sortOrder)
            {
                case "name_desc":
                    vacancies = vacancies.OrderByDescending(s => s.vacancy_name);
                    break;
                case "Date":
                    vacancies = vacancies.OrderBy(s => s.published_at);
                    break;
                case "date_desc":
                    vacancies = vacancies.OrderByDescending(s => s.published_at);
                    break;
                case "employer_name":
                    vacancies = vacancies.OrderByDescending(s => s.employer_name);
                    break;
                default:  // Name ascending 
                    vacancies = vacancies.OrderBy(s => s.vacancy_name);
                    break;
            }

            return View(vacancies);
        }

        public ViewResult Details(int id)
        {
            Vacancy vacancy = vacancyRepository.GetVacancyById(id);
            return View(vacancy);
        }
    }
}

ThirdVariant/ThirdVariant/Pages/Vacancy/Index.cshtml
@*@model PagedList.Core.IPagedList<ThirdVariant.Models.Vacancy>*@
@model Sakura.AspNetCore.IPagedList<ThirdVariant.Models.Vacancy>

@{
    ViewBag.Title = "Vacancies";
}

<h2>Vacancies</h2>


@using (Html.BeginForm("Index", "Vacancy", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}


<table>
    <tr>
        <th></th>
        <th>
            @Html.ActionLink("Vacancy Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Vacancy Name
        </th>
        <th>
            @Html.ActionLink("PublishedAt", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.ActionLink("Details", "Details", new { id=item.Name })
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.vacancy_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.published_at)
            </td>
        </tr>
    }

</table>

ThirdVariant/ThirdVariant/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ThirdVariant/ThirdVariant/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ThirdVariant/ThirdVariant/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

ThirdVariant/ThirdVariant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThirdVariant</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ThirdVariant</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*@{
                        Vars.GetVacanciesFromHh();
                    }*@
                    @*<li>@Html.ActionLink("Загрузить вакансии с hh.ru", "Index", "Vacancy")</li>*@
                    <li>@{
                        string url = Url.Action("Index", "Vacancy");
                        }
                        <input type="button" value="Загрузить вакансии с hh.ru" onclick="window.location.href = '@url'" /></li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ThirdVariant</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ThirdVariant/ThirdVariant/Views/Vacancy/Details.cshtml
@model Vacancy

<table>
    <tr>
        <th>
            <h1 style="color:black;">@Html.DisplayFor(modelItem => Model.vacancy_name)</h1>
        </th>
    </tr>
    <tr>
        <th>
            <h3 style="color:blue;">@Html.DisplayFor(modelItem => Model.employer_name)</h3>
        </th>
    </tr>
    <tr>
        <th>
            <h3 style="color:lightgray;">Уровень зарплаты</h3>
            <h5 style="color: black;">@Html.DisplayFor(modelItem => Model.salary_from)&nbsp;&nbsp;&nbsp;@Html.DisplayFor(modelItem => Model.salary_currency)</h5>
            <h3 style="color:lightgray;">Город</h3>
            <h5 style="color: black;">@Html.DisplayFor(modelItem => Model.area_name)</h5>
            <h3 style="color:lightgray;">Требуемый опыт работы</h3>
            <h5 style="color: black;">@Html.DisplayFor(modelItem => Model.experience)</h5>
        </th>
    </tr>
    <tr>
        <th>
            <br />
            @Html.Raw(Model.description)
        </th>
    </tr>
    <tr>
        <th>
            <br />
            <h3 style="color:lightgray;">Тип занятости</h3>
            <h5 style="color: black;">@Html.DisplayFor(modelItem => Model.schedule)</h5>
        </th>
    </tr>

</table>

ThirdVariant/ThirdVariant/Views/Vacancy/Index.cshtml
@model IEnumerable<ThirdVariant.Models.Vacancy>


 
<link href="/css/vacancyList.css" rel="stylesheet" type="text/css" />
    @{
        ViewBag.Title = "Найденные вакансии";
    }

    <h2>Найденные вакансии</h2>


    @using (Html.BeginForm("Index", "Vacancy", FormMethod.Get))
    {
        <p>
            Поиск по названию: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }


    <table>
        <tr>
            <th></th>
            <th>
                @Html.ActionLink("Наименование вакансии", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Компания", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Дата публикации", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("Подробно", "Details", new { id = item.id })&nbsp;&nbsp;&nbsp;
                </td>                
                <td>
                    @Html.DisplayFor(modelItem => item.vacancy_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.employer_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.published_at)
                </td>
            </tr>
        }

    </table>
    <br />